export enum UserRole {
  SUPERADMIN = "SUPERADMIN",
  CHURCH_PRESIDENT = "CHURCH_PRESIDENT",
  CHURCH_VICE_PRESIDENT = "CHURCH_VICE_PRESIDENT",
  CHURCH_SECRETARY = "CHURCH_SECRETARY",
  CHURCH_ACCOUNTANT = "CHURCH_ACCOUNTANT",
  CHURCH_WORKER = "CHURCH_WORKER",
  PRESBYTERY_MODERATOR = "PRESBYTERY_MODERATOR",
  PRESBYTERY_VICE_MODERATOR = "PRESBYTERY_VICE_MODERATOR",
  PRESBYTERY_SECRETARY = "PRESBYTERY_SECRETARY",
  PRESBYTERY_ACCOUNTANT = "PRESBYTERY_ACCOUNTANT",
  PRESBYTERY_WORKER = "PRESBYTERY_WORKER",
  PARISH_PASTOR = "PARISH_PASTOR",
  PARISH_VICE_PASTOR = "PARISH_VICE_PASTOR",
  PARISH_SECRETARY = "PARISH_SECRETARY",
  PARISH_ACCOUNTANT = "PARISH_ACCOUNTANT",
  PARISH_WORKER = "PARISH_WORKER",
  COMMUNITY_LEADER = "COMMUNITY_LEADER",
  COMMUNITY_ASSISTANT = "COMMUNITY_ASSISTANT",
  REVEREND = "REVEREND",
  DEACON = "DEACON",
  EVANGELIST = "EVANGELIST",
  MEMBER = "MEMBER",
}

export const canCreateUsers = (role: string): boolean => {
  return [UserRole.SUPERADMIN, UserRole.CHURCH_PRESIDENT, UserRole.CHURCH_SECRETARY].includes(role as UserRole);
};

export const getRoleDisplayName = (role: string): string => {
  const roleMap: Record<string, string> = {
    SUPERADMIN: "Super Admin",
    CHURCH_PRESIDENT: "Church President",
    CHURCH_VICE_PRESIDENT: "Vice President",
    CHURCH_SECRETARY: "General Secretary",
    CHURCH_ACCOUNTANT: "General Accountant",
    CHURCH_WORKER: "Synod Worker",
    PRESBYTERY_MODERATOR: "Presbytery Moderator",
    PRESBYTERY_SECRETARY: "Presbytery Secretary",
    PRESBYTERY_ACCOUNTANT: "Presbytery Accountant",
    PRESBYTERY_WORKER: "Presbytery Worker",
    PARISH_PASTOR: "Parish Pastor",
    PARISH_SECRETARY: "Parish Secretary",
    PARISH_ACCOUNTANT: "Parish Accountant",
    PARISH_WORKER: "Parish Worker",
    COMMUNITY_LEADER: "Community Leader",
    MEMBER: "Member",
  };
  return roleMap[role] || role;
};
